- name: update hostname
  become: yes
  shell: hostname '{{ inventory_hostname_short }}'
  when: ansible_hostname != inventory_hostname_short

# - name: update hostname in /etc/hostname
#   become: yes
#   lineinfile:
#     path: /etc/hostname
#     regexp: '^{{ inventory_hostname_short }}'
#     state: present
#     line: "{{ inventory_hostname_short }}"

- name: update hostname in /etc/hostname
  become: yes
  copy:
    dest: /etc/hostname
    content: "{{ inventory_hostname }}"


- name: update hostname in /etc/hosts
  become: yes
  lineinfile:
    path: /etc/hosts
    regexp: '.*{{ inventory_hostname_short }}$'
    state: present
    line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ inventory_hostname_short }}"


