- name: ensure user annsible exists
  become: yes
  user:
    name: "ansible"
    state: "present"
    shell: "/bin/bash"
    password: "{{ ansible_user_password_hash }}"


- name: add ssh-keys
  become: yes
  authorized_key:
    user: "ansible"
    key: "{{ ansible_user_public_ssh_key }}"
    exclusive: "{{ ansible_user_public_ssh_key_exclusive | default('no') }}"

- name: sudoers configuration
  become: yes
  lineinfile:
    dest: "/etc/sudoers"
    regexp: "^ansible"
    line: "ansible ALL=(ALL:ALL) NOPASSWD:ALL"
    validate: visudo -cf %s

- name: set root password
  become: yes
  user:
    name: root
    password: "{{ root_passwd_hash }}"
